package HelloNaming;


/**
* HelloNaming/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* Tuesday, March 10, 2015 2:27:55 PM GMT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
