package HelloTie;


/**
* HelloTie/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldTie.idl
* Tuesday, February 24, 2015 5:10:34 PM GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
