package HelloTie;


/**
* HelloTie/Hello_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldTie.idl
* Tuesday, February 24, 2015 5:10:34 PM GMT
*/

public class Hello_Tie extends _HelloImplBase
{

  // Constructors
  public Hello_Tie ()
  {
  }

  public Hello_Tie (HelloTie.HelloOperations impl)
  {
    super ();
    _impl = impl;
  }

  public org.omg.CORBA.Any sayHello ()
  {
    return _impl.sayHello();
  } // sayHello

  private HelloTie.HelloOperations _impl;

} // class Hello_Tie
